version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  prometheus:
    build:
      context: .
      dockerfile: dockerCompose/prometheus/Dockerfile
    ports:
    - 9090:9090
  chatting-server:
    build:
      context: .
      dockerfile: dockerCompose/spring/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - prometheus
      - kafka